### ISSUE TITLE
Issue with CLI Usage

### ISSUE THREAD

**Issue by skaschimer** [MicrosoftTranslator/DocumentTranslation#105]
I'm following the instructions provided at https://github.com/MicrosoftTranslator/DocumentTranslation/blob/master/docs/index.md.

When I get down to the CLI, the instructions are unclear or inaccurate for downloading and using the tool. for instance, if I try to set the config name, the tool tells me that name is not recognized.

In addition, when I point the CLI at a folder to translate all of the documents in the folder, I get an error message that the folder I specified in not a valid document name...

**Comment by chriswendt1** [comment]
Hi Steve, 
Can you add here what you tried and what the response was?

For the first issue: 
The configuration name is not settable. From the documentation:
>The configuration settings are stored in the file appsettings.json, in the user's roaming app settings folder, typically C:\Users<Username>\AppData\Roaming\Document Translation You may edit the file by hand, using a text editor of your choice.

For the second issue:
The tool uses the OS information about whether the given location is a file or a folder. If a folder is given, the tool will translate files in that folder, and will not recurse into subfolders. Does this explain the behavior you are seeing?

**Comment by skaschimer** [comment]
So for the first, that's fine.

For the second, it was just a folder full of files that I was using for testing the GUI. No subfolders. This was the command I gave

doctr translate "C:\Users\v-kaschimers\OneDrive - Microsoft\Documents\Accelerators\" "c:\temp\translated\" --to es

And this was the error:

Starting translation of C:\Users\v-kaschimers\OneDrive - Microsoft\Documents\Accelerators\ to es. Press Esc to cancel.
Following files were excluded due to a file type mismatch:
C:\Users\v-kaschimers\OneDrive - Microsoft\Documents\Accelerators\
List filtered to nothing. (Parameter 'filestotranslate')
ERROR: Missing or invalid credentials. Use the 'config set' command to set values.


I tried this way to (no trailing slash after the folder)

doctr translate "C:\Users\v-kaschimers\OneDrive - Microsoft\Documents\Accelerators" "c:\temp\translated" --to es

And I got the same error:

Starting translation of C:\Users\v-kaschimers\OneDrive - Microsoft\Documents\Accelerators to es. Press Esc to cancel.
Following files were excluded due to a file type mismatch:
C:\Users\v-kaschimers\OneDrive - Microsoft\Documents\Accelerators
List filtered to nothing. (Parameter 'filestotranslate')
ERROR: Missing or invalid credentials. Use the 'config set' command to set values.

Steve

**Comment by chriswendt1** [comment]
Hi Steve,

There is a real bug here: the message `ERROR: Missing or invalid credentials. Use the 'config set' command to set values.` shows up when the source folder is empty. There is most likely nothing wrong with your credentials. 

Use the command `doctr config test` to get a hint whether your credentials are valid and accepted by the service. 

It is by current design that the tool does not recurse through subfolders.

The following shows the translation of a set of files in a folder with one file being untranslatable.
Followed by the translation attempt of an empty folder.

![Screenshot 2022-11-21 120501](https://user-images.githubusercontent.com/11096941/203148392-364afb83-bd20-44d3-96db-cb9732c5aa24.png)

I will treat this issue in the sense of:
**Translation of an empty folder causes an erroneous error message about invalid or missing credentials**

Let me know as a new "issue" if recursing through subfolders is essential for you. I am happy to add this as a feature.

**Comment by skaschimer** [comment]
Hi Chris

Thanks for the reply. When I do doctr config test, it tests fine. Are there any limitations to the folder that the files can be in? Mine were in c:\temp yours are in a folder on d:\.

Subfolders... that's fine I get that that's not the design right now and its not a hard and fast requirement.

Thanks again

Steve

**Comment by chriswendt1** [comment]
You tried to translate a OneDrive folder. Can it be that the source files were not physically present on the drive yet? Explorer needs to show the green circle checkmark for the file(s) in question. I am not sure the tool would invoke OneDrive's just in time download. 
I am quite sure that the target folder doesn't matter, as long as you have write permission to it.

**Comment by chriswendt1** [comment]
The failure to translate OneDrive folders was a stupid mistake in the logic for checking the file attributes, and a simple and safe fix.

**Comment by chriswendt1** [comment]
@skaschimer Closing this, pursuing the two issues in #106 and #107.

**Comment by chriswendt1** [comment]
Both the issues raised here are now fixed in code. Wait for the updated binaries or compile from current code.
