### ISSUE TITLE
Some more useful information in Status bar 

### ISSUE THREAD

**Issue by krishna-doss-mohan** [MicrosoftTranslator/DocumentTranslation#36]
Status bar could show
1) size of file - shown now
2) count of characters translated - earlier bits had this - now missig
3) time to upload = job created time - 'Translate Documents' button press time.
4) time in queue = job start time - job created time 
5) time in translate = job complete time - job start time 
6) time to download = files downloaded to target folder - job complete time
![image](https://user-images.githubusercontent.com/58462203/122630689-7f952380-d07a-11eb-8ee9-b7820fb8aa43.png)

**Comment by chriswendt1** [comment]
[doctrLog.txt](https://github.com/MicrosoftTranslator/DocumentTranslation/files/6681462/doctrLog.txt)
The count of characters translated comes from the service. If the server reports zero, the status bar suppresses the display. 
The server reports zero. You can see the every server response in the output Window when running in VS. Look at the last one. 
The log in C:\Users\wendt\AppData\Roaming\Document Translation\doctrLog.txt contains detailed timing information. The number following the colon is the time since "Translate Documents" button press.
