### ISSUE TITLE
Performance Wait Times on Selecting Close to 10 Languages

### ISSUE THREAD

**Issue by Akeung8** [MicrosoftTranslator/DocumentTranslation#72]
Hi Chris,

Thanks again for creating the new and improved multiple translation functionality. Greatly appreciated. Our team conducted testing on translating a document having selected French, German, Italian, Japanese, Portuguese, Russian, Chinese and Spanish and I found that the app was continuously loading. Wanted to see if you also saw similar performance wait times on your end. I unfortunately couldn't test the glossary yet for multiple languages but once completed will add a comment on that to let you know.

**Comment by chriswendt1** [comment]
Chinese (Simplified and Traditional) and Portuguese (Portugal) are the problem.
Can't translate to those, even when by itself as a single language.

**Comment by chriswendt1** [comment]
The problem was: App uses the language ID as part of the Azure blob container name. Azure container names must be all lowercase. Some language IDs contain uppercase characters (pt-PT, zh-Hans), so those languages were failing. 
Fixed by lowercasing the language ID before use in the container name in version 0.8.7.1.
