### ISSUE TITLE
can translate py files?

### ISSUE THREAD

**Issue by johnfelipe** [MicrosoftTranslator/DocumentTranslation#97]
https://github.com/Bryan-Guner-Backup/DOWN_ARCHIVE_V2/blob/master/LAMBDA_LABS/deprecated-family-promise-spokane-ds-b/fps_dashboard/des_statistics.py

i need translate to spanish all prhases and strings into " "
is possible with this app
or can u refer any app in nodejs, c# or even python for translate that sources?

**Comment by chriswendt1** [comment]
You want to keep your string resources separate from your code, so that you have a single instance of your code and multiple string resource files, one or more per language, that your code loads depending on the client language.
This
https://stackoverflow.com/questions/5719502/string-resources-in-python-google-app-engine
recommends storing the display strings a plain text file, which you can translate using any method, for instance this app.

**Comment by johnfelipe** [comment]
Do u know something like this?
https://github.com/menthays/markdown-translator

that is for md files, i need something like that but for py files

**Comment by chriswendt1** [comment]
I understand your question. But that's not a sustainable way to manage your localized resources. You need to separate them from your code.
In Python you have no way to mark up the translatable strings, which will wreak havoc with file names or other strings values that need to be controlled by the developer.
Please take my advice and separate the localizable strings from your code.

Chris..
________________________________

**Comment by johnfelipe** [comment]
do u have a github repository in python or nodejs for separate, or regex
for doing in notepad++?

**Comment by chriswendt1** [comment]
You will need to do that by hand. Any code won't know which string are localizable and which ones aren't.

Chris..
________________________________
